# Generated by Django 3.1.5 on 2021-02-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20210226_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='preparation_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
